### ISSUE TITLE
Multiple concurrent clients

### ISSUE THREAD

**Issue by MoffKalast** [v-kiniv/rws#17]
So this is something more of a suggestion than a bug report, I've noticed that there can seemingly only be one client connected to one topic at a time.

If I e.g. open two browser windows that both subscribe to the same long list of topics at roughly the same time, they'll seemingly split the list in two, one receiving some and the other what's left depending on which connection gets there first. I suspect some of the bugs I've seen in the past were made a bit more confusing due to this.

There is the issue of course that mobile browser suspended clients or background windows will pull resources when not actually being used, which serving only the latest one solves, but it also prevents multiple instances of the same app running concurrently. Besides, the watchdog should take care of those instances to some extent, right?

The rosbridge default behaviour is to send all data to all clients, so it would be nice to have parity there.

**Comment by v-kiniv** [comment]
Sorry for late reply, had other things going. So I tested this by running a full stack project with lidar, camera feed, nav2, etc., connected from 2 Foxglove clients(connected to the same set of topics) and everything seems to work fine. Can you please test with Foxglove?
Maybe it's a roslibjs thing related to https://github.com/v-kiniv/rws/issues/6, although I'm not sure because you mention separate browser windows.


> Besides, the watchdog should take care of those instances to some extent

Yes, watchdog uses an active ping-pong mechanism to drop clients that don't respond in time.

**Comment by v-kiniv** [comment]
I tested more, also with Vizanti instead of Foxglove, and I noticed that the robot model is stuck(unlike Rosbridge), after reconnecting from the second client, and this is consistent with what you found regarding /tf and /tf_static. So looked at the transform topics and I think I found the source of the issue, it's related to QoS and caching(again). RWS caches topic subscriptions and this causes problems if topic QoS is set to Transient Local. New clients do not receive persisting messages from such topics. I fixed it by checking QoS before cache/do not cache decision. Please check https://github.com/v-kiniv/rws/pull/18.

Regarding watchdog, let's discuss in separate issue if the the problem persist.

As a side note, I noticed that that "Costmap Colouring" option for Map widget in Vizanti does not work with Rosbridge but works fine with RWS. Did you notice something similar?

Top image RWS, bottom image Rosbridge:
<img width="379" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/32e4c67c-04ff-4402-9666-4367382c68e4">
<img width="413" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/1f4d4d91-1f4d-4212-a192-42d9ec554824">

**Comment by MoffKalast** [comment]
I've tried out #18, it fixes it perfectly on my end. 👍 I've tested up to 8 concurrent Vizanti instances and a Foxglove client all at the same time and it seems to work very well.

> As a side note, I noticed that "Costmap Colouring" option for Map widget in Vizanti does not work with Rosbridge but works fine with RWS. Did you notice something similar?

Hmm, well I've fixed some issues with latched maps not loading at all recently, since Firefox has a bug with rendering offscreen canvases in workers, but that should be all fixed and on Chromium it was never a problem. 

Does the regular colouring work? There really shouldn't be any difference between the two, just that it takes an additional message to re-render the new colour scheme if it's swapped, which is sometimes an issue for latched maps. What I think happens is that when the web client unregisters and subscribes, rosbridge caches the topic, so it doesn't get and forward the latched message again, because it's already received it once on the ROS side. But I don't think I've seen it get into this state consistently.

In my current nav2 demo setup in a VM it seems to be working fine for both costmaps and regular maps, on rosbridge, rws, firefox and chromium and all combinations of those.

> Regarding watchdog, let's discuss in separate issue if the problem persist.

Well I'm no longer seeing those repeat drops and reconnects now that all clients run fine, so I figure it was related. I'll have to do some field tests with it on and off to see what happens at extreme wifi range and if it there's any benefit to having it disabled or the opposite. It might be beneficial to leave it on and reduce tcp congestion when there's extreme packet loss I guess.

**Comment by v-kiniv** [comment]
> I've tried out https://github.com/v-kiniv/rws/pull/18, it fixes it perfectly on my end. 👍 I've tested up to 8 concurrent Vizanti instances and a Foxglove client all at the same time and it seems to work very well.

Great, I'll merge the PR then.

> Does the regular colouring work on your end? 

Here is the regular colouring. It looks like the same situation, but the other way around.
Top image - RWS, bottom - Rosbridge:

<details>
<summary>Chrome 122.0.6261.94 (Mac), Non-Coloured</summary>
<img width="404" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/88d3bd83-e151-4ea1-8a80-b86e6c8fdfad">

<img width="403" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/4eaa3fee-64b1-4f22-a202-ef65420db199">
</details>

<details>
<summary>Firefox 123.0 (Ubuntu), Non-Coloured</summary>

<img width="539" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/34049958-4cb2-416b-8917-e0e1925b79c0">

<img width="540" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/99f98cdf-5b3e-494d-93fa-eb101d762827">

</details>

And here's coloured again but in Firefox:
<details>
<summary>Firefox 123.0 (Ubuntu), Coloured</summary>

<img width="541" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/46a02e5d-b375-4141-91a9-c220a5edcdf9">

<img width="542" alt="image" src="https://github.com/v-kiniv/rws/assets/1661016/022c0070-1cdb-4050-a119-ad1a781e8068">

</details>

**Comment by MoffKalast** [comment]
> Great, I'll merge the PR then.

Cool, we can close then.

> Here is the regular colouring. It looks like the same situation, but the other way around.

Ok that's genuinely weird. Are you using the same config and topics for the first two (global settings, export layout, then import)? The inflated one should be set to translucent + costmap rendering. But the lack of gray areas is puzzling regardless and I have seen it before a while back, live on a robot doing slam. At the time I figured it's something to do with the slam_toolbox config since I was seeing the same weird thing in rviz as well, but didn't check what happens over rosbridge at the time.

I've tested all four combinations + rviz with the two setups I have on hand and I don't see any difference with the same config, although rviz does render costmaps slightly differently.

Nav2 demo with turtlebot3 and premade map published by the map_server:

![image](https://github.com/v-kiniv/rws/assets/9977799/8d8bcdb8-4182-4c1b-9601-0141cab7b702)

Slam toolbox on some bag data:

![image](https://github.com/v-kiniv/rws/assets/9977799/8f6f88b0-5894-435a-b802-9247a4a17990)

That last rws on firefox looks like there's some tf missing, but it's just the bag ending and it looked the same before that.

Any chance you could send over a short bag of that test setup you've got if it's consistently repeatable? It would be a great help in figuring this out. Maybe we can move the discussion over to https://github.com/MoffKalast/vizanti/issues since it's a bit off topic for this thread.

**Comment by v-kiniv** [comment]
> Any chance you could send over a short bag of that test setup you've got if it's consistently repeatable?

Sure.

> Maybe we can move the discussion over to https://github.com/MoffKalast/vizanti/issues since it's a bit off topic for this thread.

Agree, I'll create an issue.



Thanks again for your help in fixing yet another bug!
